const params = new URLSearchParams(location.search);
const clean = (value, fallback) => String(value || "").trim().toLowerCase().replace(/[^a-z0-9-]/g, "") || fallback;
const trip = clean(params.get("trip"), "kyrgyzstan-2026");
const chapter = clean(params.get("chapter") || params.get("day") || params.get("day_tag"), "day02");
const base = `data/${trip}/${chapter}`; const paths = { photos: `${base}-photos.json`, author: `${base}-author-review.json`, final: `${base}-final-review.json`, storyboard: `${base}-storyboard.json` };
const diagnostics = []; const photoId = photo => String(photo.photo_id || photo.public_id || photo.key || ""); const items = value => Array.isArray(value) ? value : value?.items || []; const fp = value => value?.photos_fingerprint || "legacy-no-fingerprint";
let photoPicker;
const heroTitle = document.querySelector("#heroTitle"), heroSubtitle = document.querySelector("#heroSubtitle"), heroHeader = document.querySelector("#heroHeader"), chapterTitle = document.querySelector("#chapterTitle"), chapterIntro = document.querySelector("#chapterIntro"), storyPhotos = document.querySelector("#storyPhotos"), backstagePhotos = document.querySelector("#backstagePhotos"), previewNote = document.querySelector("#previewNote");
const esc = value => String(value || "").replace(/[&<>"]/g, character => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[character]);
const imgUrl = (url, width = 1800) => url.includes("/image/upload/") ? url.replace("/image/upload/", `/image/upload/f_auto,q_auto,w_${width}/`) : url;
const previewImage = (photo, width = 1400) => photo.key ? `https://upload.owntravel.ru/thumbnail/${String(photo.key).split("/").map(encodeURIComponent).join("/")}?w=${width}` : imgUrl(photo.url, width);
async function load(path, optional = false) { const response = await fetch(`${path}?v=${Date.now()}`, { cache: "no-store" }); if (!response.ok) { if (optional && response.status === 404) return null; throw new Error(`${path}: HTTP ${response.status}`); } diagnostics.push(`${path}: OK`); return response.json(); }
function exact(inventory, artifact, label) { const expected = new Set(items(inventory).map(photoId)); const actual = items(artifact).map(photoId); if (actual.length !== expected.size || new Set(actual).size !== actual.length || actual.some(id => !expected.has(id))) throw new Error(`${label} не соответствует исходному набору`); if (fp(inventory) !== "legacy-no-fingerprint" && fp(artifact) !== fp(inventory)) throw new Error(`${label}: устаревший fingerprint`); }
function sceneHtml(scene, map, index) { const photos = (scene.photos || []).map(id => map.get(id)).filter(Boolean); if (!photos.length) return ""; return `<section class="scene"><div class="scene-copy"><p class="eyebrow">${String(index + 1).padStart(2, "0")} · ${esc(scene.title)}</p><p>${esc(scene.text)}</p></div><div class="scene-photos ${photos.length > 1 ? "multi" : ""}">${photos.map(photo => `<figure class="scene-photo"><img src="${esc(previewImage(photo))}" alt="" loading="lazy" decoding="async"></figure>`).join("")}</div></section>`; }
async function init() {
  const [inventory, author, final, storyboard] = await Promise.all([load(paths.photos), load(paths.author), load(paths.final, true), load(paths.storyboard)]);
  exact(inventory, author, "author-review"); if (author.schema_version >= 2 && author.approval !== "photo_selection_approved") throw new Error("первое утверждение фотографий отсутствует"); if (final) exact(inventory, final, "final-review");
  const source = final || author; if (storyboard.photos_fingerprint && storyboard.photos_fingerprint !== fp(inventory)) throw new Error("storyboard использует другой набор фотографий");
  const storyboardReviewSource = storyboard.final_review_source || storyboard.review_source || storyboard.author_review_source;
  if (![paths.author, paths.final].includes(storyboardReviewSource)) throw new Error("storyboard не связан с утверждённым author-review");
  const map = new Map(items(inventory).map(photo => [photoId(photo), photo])); const selected = new Map(items(source).map(item => [photoId(item), item]));
  const hero = items(source).find(item => item.status === "hero"); if (!hero || !map.has(photoId(hero))) throw new Error("главное фото не найдено");
  const chapterData = storyboard.chapter || {}; document.title = `Предпросмотр · ${chapterData.title || chapter}`; heroTitle.textContent = chapterData.title || chapter; heroSubtitle.textContent = chapterData.subtitle || ""; chapterTitle.textContent = chapterData.title || chapter; chapterIntro.textContent = chapterData.intro || ""; heroHeader.style.backgroundImage = `linear-gradient(180deg,rgba(0,0,0,.04),rgba(0,0,0,.68)),url(${previewImage(map.get(photoId(hero)), 1600)})`;
  storyPhotos.innerHTML = (storyboard.scenes || []).map((scene, index) => sceneHtml(scene, map, index)).join("");
  backstagePhotos.innerHTML = items(source).filter(item => item.status === "backstage").map(item => { const photo = map.get(photoId(item)); return photo ? `<article class="backstage-card"><img src="${esc(previewImage(photo, 720))}" alt="" loading="lazy" decoding="async"><p>${esc(item.label)}</p></article>` : ""; }).join("");
  previewNote.textContent = `Только утверждённый источник: ${final ? paths.final : paths.author}. Storyboard: ${paths.storyboard}. Fingerprint: ${fp(inventory)}.`;
  document.querySelector("#approvePreviewBtn").onclick = async () => { const approval = { schema_version: 1, trip, chapter, status: "preview_approved", photos_fingerprint: fp(inventory), author_review_source: paths.author, storyboard_source: paths.storyboard, approved_at: new Date().toISOString() }; const status = document.querySelector("#authorNoteStatus"); try { if (!photoPicker) throw new Error("Подключение отправки ещё загружается"); status.textContent = "Сохраняем второе утверждение…"; const result = await photoPicker.approvePreview(approval); status.innerHTML = `Preview утверждён. Публикация не выполнена. <a href="${esc(result.status_url)}">Вернуться к статусу путешествия</a>`; } catch (error) { status.textContent = `Не удалось сохранить утверждение: ${error.message}`; } };
}
init().catch(error => { storyPhotos.innerHTML = `<div class="loading"><b>Предпросмотр заблокирован.</b><br>${esc(error.message)}<br><small>${esc(diagnostics.join(" · "))}</small></div>`; document.querySelector("#approvePreviewBtn").disabled = true; });
Promise.all([import("./lib/photo-services-config.mjs?v=24"), import("./google-photos-picker.js?v=24")]).then(async ([{ validatePhotoServicesConfig }, { GooglePhotosPicker }]) => { const response = await fetch("./config/photo-services.json", { cache: "no-store" }); photoPicker = new GooglePhotosPicker(validatePhotoServicesConfig(await response.json())); }).catch(error => diagnostics.push(`approval: ${error.message}`));
